### ISSUE TITLE
not able to start the example

### ISSUE THREAD

**Issue by vu3mmg** [h4v0kr/quorum-docker#2]
Hi,
I am not able to start the example .
I am getting the following error  when I run raft-start.sh 
could you please let me know whether I am missing some thing .
-Mahesh

root@04bcd4846614:/quorum-examples/examples/7nodes# ./raft-start.sh 
[*] Starting Constellation nodes
[*] Starting node 1
[*] Starting node 2
[*] Starting node 3
[*] Starting node 4
[*] Starting node 5
[*] Starting node 6
[*] Starting node 7
[*] Waiting for nodes to start
[*] Sending first transaction
panic: MustNew error: Get http+unix://c/upcheck: dial unix: missing address

goroutine 1 [running]:
panic(0xc1f6e0, 0xc4201d8c00)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc42001000f, 0x8, 0xc42001000f)
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:76 +0x114
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0xd5a99d, 0xe, 0x1538f40, 0xc42004bea0)
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:19 +0x52
github.com/ethereum/go-ethereum/private.init()
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:22 +0x67
github.com/ethereum/go-ethereum/core.init()
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm_env.go:165 +0xf4
github.com/ethereum/go-ethereum/cmd/utils.init()
	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/version.go:65 +0x76
main.init()
	github.com/ethereum/go-ethereum/cmd/geth/_obj/_cgo_import.go:6 +0x58

**Comment by tkddn204** [comment]
I've also tried it, but it does not work well.
